import baseConfig from "./vitest.e2e.config";

export default {
  ...baseConfig,
  test: {
    ...baseConfig.test,
    include: [
      "test/**/*.live.test.ts",
      "test/**/*.live.test.tsx",
      "test/**/*-live.test.ts",
      "test/**/*-live.test.tsx",
      "test/**/*.live.e2e.test.ts",
      "test/**/*.live.e2e.test.tsx",
      "test/**/*.real.e2e.test.ts",
      "test/**/*.real.e2e.test.tsx",
      "test/**/*-live.e2e.test.ts",
      "test/**/*-live.e2e.test.tsx",
      "eliza/packages/agent/test/**/*.live.test.ts",
      "eliza/packages/agent/test/**/*.live.test.tsx",
      "eliza/packages/agent/test/**/*-live.test.ts",
      "eliza/packages/agent/test/**/*-live.test.tsx",
      "eliza/packages/agent/test/**/*.live.e2e.test.ts",
      "eliza/packages/agent/test/**/*.live.e2e.test.tsx",
      "eliza/packages/agent/test/**/*.real.e2e.test.ts",
      "eliza/packages/agent/test/**/*.real.e2e.test.tsx",
      "eliza/packages/agent/test/**/*-live.e2e.test.ts",
      "eliza/packages/agent/test/**/*-live.e2e.test.tsx",
      "eliza/packages/agent/test/**/*.live.test.ts",
      "eliza/packages/agent/test/**/*.live.test.tsx",
      "eliza/packages/agent/test/**/*-live.test.ts",
      "eliza/packages/agent/test/**/*-live.test.tsx",
      "eliza/packages/agent/test/**/*.live.e2e.test.ts",
      "eliza/packages/agent/test/**/*.live.e2e.test.tsx",
      "eliza/packages/agent/test/**/*.real.e2e.test.ts",
      "eliza/packages/agent/test/**/*.real.e2e.test.tsx",
      "eliza/packages/agent/test/**/*-live.e2e.test.ts",
      "eliza/packages/agent/test/**/*-live.e2e.test.tsx",
      "eliza/packages/app-core/test/**/*.live.test.ts",
      "eliza/packages/app-core/test/**/*.live.test.tsx",
      "eliza/packages/app-core/test/**/*-live.test.ts",
      "eliza/packages/app-core/test/**/*-live.test.tsx",
      "eliza/packages/app-core/test/**/*.live.e2e.test.ts",
      "eliza/packages/app-core/test/**/*.live.e2e.test.tsx",
      "eliza/packages/app-core/test/**/*.real.e2e.test.ts",
      "eliza/packages/app-core/test/**/*.real.e2e.test.tsx",
      "eliza/packages/app-core/test/**/*-live.e2e.test.ts",
      "eliza/packages/app-core/test/**/*-live.e2e.test.tsx",
      "eliza/packages/app-core/test/**/*.live.test.ts",
      "eliza/packages/app-core/test/**/*.live.test.tsx",
      "eliza/packages/app-core/test/**/*-live.test.ts",
      "eliza/packages/app-core/test/**/*-live.test.tsx",
      "eliza/packages/app-core/test/**/*.live.e2e.test.ts",
      "eliza/packages/app-core/test/**/*.live.e2e.test.tsx",
      "eliza/packages/app-core/test/**/*.real.e2e.test.ts",
      "eliza/packages/app-core/test/**/*.real.e2e.test.tsx",
      "eliza/packages/app-core/test/**/*-live.e2e.test.ts",
      "eliza/packages/app-core/test/**/*-live.e2e.test.tsx",
    ],
    exclude: ["dist/**", "**/node_modules/**"],
  },
};
