export {
  COMPANION_OVERLAY_TABS,
  ACCENT_COLORS,
  TOP_BAR_COLORS,
  tabFlags,
  type TabFlags,
  overlayBackdropClass,
  cardSizeClass,
  cardBackground,
  cardBorderColor,
  cardBoxShadow,
  accentVar,
  accentSubtleVar,
  accentRgbVar,
  accentForegroundVar,
  viewWrapperOverflow,
  viewWrapperPadding,
  viewWrapperStyle,
} from "@elizaos/app-companion";
