import "@miladyai/capacitor-camera";
import "@miladyai/capacitor-canvas";
import "@miladyai/capacitor-gateway";
import "@miladyai/capacitor-location";
import "@miladyai/capacitor-mobile-signals";
import "@miladyai/capacitor-screencapture";
import "@miladyai/capacitor-swabble";
import "@miladyai/capacitor-talkmode";
import "@miladyai/capacitor-websiteblocker";
