export const KNOWN_IPC_CHANNELS = [
  "agent:restart",
  "agent:start",
  "agent:status",
  "agent:stop",
  "camera:capturePhoto",
  "camera:checkPermissions",
  "camera:getDevices",
  "camera:getRecordingState",
  "camera:requestPermissions",
  "camera:startPreview",
  "camera:startRecording",
  "camera:stopPreview",
  "camera:stopRecording",
  "camera:switchCamera",
  "canvas:a2uiPush",
  "canvas:a2uiReset",
  "canvas:createWindow",
  "canvas:destroyWindow",
  "canvas:eval",
  "canvas:focus",
  "canvas:getBounds",
  "canvas:hide",
  "canvas:listWindows",
  "canvas:navigate",
  "canvas:resize",
  "canvas:setBounds",
  "canvas:show",
  "canvas:snapshot",
  "contextMenu:askAgent",
  "contextMenu:createSkill",
  "contextMenu:quoteInChat",
  "contextMenu:saveAsCommand",
  "desktop:beep",
  "desktop:clearClipboard",
  "desktop:closeNotification",
  "desktop:closeWindow",
  "desktop:createTray",
  "desktop:destroyTray",
  "desktop:focusWindow",
  "desktop:getAutoLaunchStatus",
  "desktop:getPath",
  "desktop:getPowerState",
  "desktop:getVersion",
  "desktop:getWindowBounds",
  "desktop:hideWindow",
  "desktop:isPackaged",
  "desktop:isShortcutRegistered",
  "desktop:isWindowFocused",
  "desktop:isWindowMaximized",
  "desktop:isWindowMinimized",
  "desktop:isWindowVisible",
  "desktop:maximizeWindow",
  "desktop:minimizeWindow",
  "desktop:openExternal",
  "desktop:quit",
  "desktop:readFromClipboard",
  "desktop:registerShortcut",
  "desktop:relaunch",
  "desktop:setAlwaysOnTop",
  "desktop:setAutoLaunch",
  "desktop:setFullscreen",
  "desktop:setOpacity",
  "desktop:setTrayMenu",
  "desktop:setWindowBounds",
  "desktop:setWindowOptions",
  "desktop:showItemInFolder",
  "desktop:showNotification",
  "desktop:showWindow",
  "desktop:unmaximizeWindow",
  "desktop:unregisterAllShortcuts",
  "desktop:unregisterShortcut",
  "desktop:updateTray",
  "desktop:writeToClipboard",
  "gateway:getDiscoveredGateways",
  "gateway:isDiscovering",
  "gateway:startDiscovery",
  "gateway:stopDiscovery",
  "location:clearWatch",
  "location:getCurrentPosition",
  "location:getLastKnownLocation",
  "location:watchPosition",
  "permissions:check",
  "permissions:checkFeature",
  "permissions:clearCache",
  "permissions:getAll",
  "permissions:getPlatform",
  "permissions:isShellEnabled",
  "permissions:openSettings",
  "permissions:request",
  "permissions:setShellEnabled",
  "screencapture:captureWindow",
  "screencapture:getRecordingState",
  "screencapture:getSources",
  "screencapture:isFrameCaptureActive",
  "screencapture:pauseRecording",
  "screencapture:resumeRecording",
  "screencapture:saveScreenshot",
  "screencapture:startFrameCapture",
  "screencapture:startRecording",
  "screencapture:stopFrameCapture",
  "screencapture:stopRecording",
  "screencapture:takeScreenshot",
  "swabble:audioChunk",
  "swabble:getConfig",
  "swabble:isListening",
  "swabble:isWhisperAvailable",
  "swabble:start",
  "swabble:stop",
  "swabble:updateConfig",
  "talkmode:audioChunk",
  "talkmode:getState",
  "talkmode:getWhisperInfo",
  "talkmode:isEnabled",
  "talkmode:isSpeaking",
  "talkmode:isWhisperAvailable",
  "talkmode:speak",
  "talkmode:start",
  "talkmode:stop",
  "talkmode:stopSpeaking",
  "talkmode:updateConfig",
] as const;

export type KnownIpcChannel = (typeof KNOWN_IPC_CHANNELS)[number];

export type RuntimeBridgeIpcChannel =
  | `${string}-${string}`
  | `event-${string}-${string}`
  | `event-add-${string}`
  | `event-remove-${string}-${string}`;

export type IpcChannel = KnownIpcChannel | RuntimeBridgeIpcChannel;

const KNOWN_IPC_CHANNEL_SET = new Set<string>(KNOWN_IPC_CHANNELS);

export function isKnownIpcChannel(channel: string): channel is KnownIpcChannel {
  return KNOWN_IPC_CHANNEL_SET.has(channel);
}
