name: Bug Report
description: Report a bug you found while using Milaidy
labels: ["bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Describe the issue you encountered.
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Numbered steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected result.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe the actual result.
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Select your operating system.
      options:
        - macOS
        - Windows
        - Linux
        - Other
    validations:
      required: true

  - type: input
    id: node_version
    attributes:
      label: Node Version
      description: e.g. 22.x
      placeholder: 22.x
    validations:
      required: false

  - type: input
    id: model_provider
    attributes:
      label: Model Provider
      description: e.g. Anthropic, OpenAI, Ollama
      placeholder: Anthropic / OpenAI / Ollama
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant error output or logs
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable
      placeholder: Add screenshots, screen recordings, or links here.
    validations:
      required: false
