name: milaidy
version: '2.0.0-alpha.7'
summary: Personal AI assistant built on ElizaOS
description: |
  Milaidy is a personal AI assistant you run on your own devices, built on
  ElizaOS. It provides zero-config onboarding, multi-provider AI support,
  a web dashboard, and a plugin system for extensibility.

  Features:
  - Interactive setup on first run — pick a name, personality, and AI provider
  - Support for Anthropic (Claude), OpenAI, Google Gemini, Ollama, and more
  - Web dashboard at http://localhost:18789
  - Plugin system for extensibility
  - Web3 wallet integration (EVM + Solana)
  - Desktop apps for macOS, Windows, and Linux

  Quick start: milaidy start

grade: devel
confinement: classic
base: core22
license: MIT
website: https://milady.ai
source-code: https://github.com/milady-ai/milaidy
issues: https://github.com/milady-ai/milaidy/issues

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

apps:
  milaidy:
    command: bin/milaidy-wrapper
    environment:
      PATH: $SNAP/node/bin:$SNAP/usr/bin:$SNAP/bin:$PATH
      NODE_PATH: $SNAP/lib/milaidy/node_modules

parts:
  node:
    plugin: nil
    override-build: |
      set -eu
      NODE_VERSION="22.12.0"
      ARCH=$(dpkg --print-architecture)
      case "$ARCH" in
        amd64) NODE_ARCH="x64" ;;
        arm64) NODE_ARCH="arm64" ;;
        *) echo "Unsupported arch: $ARCH"; exit 1 ;;
      esac
      curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-${NODE_ARCH}.tar.xz" \
        | tar xJ --strip-components=1 -C "$CRAFT_PART_INSTALL"
      "$CRAFT_PART_INSTALL/bin/node" --version
      "$CRAFT_PART_INSTALL/bin/npm" --version
    organize:
      '*': node/

  milaidy:
    after: [node]
    plugin: nil
    source: .
    override-build: |
      set -eu
      export PATH="$CRAFT_STAGE/node/bin:$PATH"
      npm ci --ignore-scripts || npm install --ignore-scripts
      npm run build || true
      mkdir -p "$CRAFT_PART_INSTALL/lib/milaidy"
      cp -r dist/ "$CRAFT_PART_INSTALL/lib/milaidy/" 2>/dev/null || true
      cp milaidy.mjs "$CRAFT_PART_INSTALL/lib/milaidy/"
      cp package.json "$CRAFT_PART_INSTALL/lib/milaidy/"
      cp plugins.json "$CRAFT_PART_INSTALL/lib/milaidy/"
      cd "$CRAFT_PART_INSTALL/lib/milaidy"
      cp "$CRAFT_PART_SRC/package.json" .
      npm install --production --ignore-scripts 2>/dev/null || true
      mkdir -p "$CRAFT_PART_INSTALL/bin"
      printf '#!/bin/sh\nexec "$SNAP/node/bin/node" "$SNAP/lib/milaidy/milaidy.mjs" "$@"\n' > "$CRAFT_PART_INSTALL/bin/milaidy-wrapper"
      chmod +x "$CRAFT_PART_INSTALL/bin/milaidy-wrapper"
    build-packages:
      - curl
