import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { releaseData } from "../generated/release-data";

const here = path.dirname(fileURLToPath(import.meta.url));
const releaseDataPath = path.resolve(here, "../generated/release-data.ts");

describe("generated release data", () => {
  it("carries the generator header", () => {
    const source = readFileSync(releaseDataPath, "utf8");

    expect(
      source.startsWith(
        "// AUTO-GENERATED by scripts/write-homepage-release-data.mjs. Do not edit manually.\n",
      ),
    ).toBe(true);
  });

  it("records the generation timestamp", () => {
    expect(Date.parse(releaseData.generatedAt)).not.toBeNaN();
  });
});
