require_relative '../../../../node_modules/.bun/@capacitor+ios@8.2.0+15945e198350fa93/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.bun/@capacitor+ios@8.2.0+15945e198350fa93/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.bun/@capacitor+ios@8.2.0+15945e198350fa93/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../../node_modules/.bun/@capacitor+app@8.0.1+15945e198350fa93/node_modules/@capacitor/app'
  pod 'CapacitorHaptics', :path => '../../../../node_modules/.bun/@capacitor+haptics@8.0.0+15945e198350fa93/node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../../../node_modules/.bun/@capacitor+keyboard@8.0.0+15945e198350fa93/node_modules/@capacitor/keyboard'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/.bun/@capacitor+preferences@8.0.1+15945e198350fa93/node_modules/@capacitor/preferences'
  pod 'CapacitorStatusBar', :path => '../../../../node_modules/.bun/@capacitor+status-bar@8.0.1+15945e198350fa93/node_modules/@capacitor/status-bar'
  pod 'MiladyaiCapacitorAgent', :path => '../../plugins/agent'
  pod 'MiladyaiCapacitorCamera', :path => '../../plugins/camera'
  pod 'MiladyaiCapacitorCanvas', :path => '../../plugins/canvas'
  pod 'MiladyaiCapacitorGateway', :path => '../../plugins/gateway'
  pod 'MiladyaiCapacitorLocation', :path => '../../plugins/location'
  pod 'MiladyaiCapacitorScreencapture', :path => '../../plugins/screencapture'
  pod 'MiladyaiCapacitorSwabble', :path => '../../plugins/swabble'
  pod 'MiladyaiCapacitorTalkmode', :path => '../../plugins/talkmode'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
