require_relative '../../../../node_modules/.bun/@capacitor+ios@8.3.0+db0c1b46371b240c/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.bun/@capacitor+ios@8.3.0+db0c1b46371b240c/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.bun/@capacitor+ios@8.3.0+db0c1b46371b240c/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../../../node_modules/.bun/@capacitor+app@8.1.0+db0c1b46371b240c/node_modules/@capacitor/app'
  pod 'CapacitorKeyboard', :path => '../../../../node_modules/.bun/@capacitor+keyboard@8.0.0+db0c1b46371b240c/node_modules/@capacitor/keyboard'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/.bun/@capacitor+preferences@8.0.1+db0c1b46371b240c/node_modules/@capacitor/preferences'
  pod 'CapacitorStatusBar', :path => '../../../../node_modules/.bun/@capacitor+status-bar@8.0.2+db0c1b46371b240c/node_modules/@capacitor/status-bar'
  pod 'MiladyaiCapacitorAgent', :path => '../../../../eliza/packages/native-plugins/agent'
  pod 'MiladyaiCapacitorCamera', :path => '../../../../eliza/packages/native-plugins/camera'
  pod 'MiladyaiCapacitorCanvas', :path => '../../../../eliza/packages/native-plugins/canvas'
  pod 'MiladyaiCapacitorGateway', :path => '../../../../eliza/packages/native-plugins/gateway'
  pod 'MiladyaiCapacitorLocation', :path => '../../../../eliza/packages/native-plugins/location'
  pod 'MiladyaiCapacitorMobileSignals', :path => '../../../../eliza/packages/native-plugins/mobile-signals'
  pod 'MiladyaiCapacitorScreencapture', :path => '../../../../eliza/packages/native-plugins/screencapture'
  pod 'MiladyaiCapacitorSwabble', :path => '../../../../eliza/packages/native-plugins/swabble'
  pod 'MiladyaiCapacitorTalkmode', :path => '../../../../eliza/packages/native-plugins/talkmode'
  pod 'MiladyaiCapacitorWebsiteblocker', :path => '../../../../eliza/packages/native-plugins/websiteblocker'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
