// Onboarding wizard graph (pure); see docs/guides/onboarding-ui-flow.md
export {
  canRevertOnboardingTo,
  getFlaminaTopicForOnboardingStep,
  getOnboardingNavMetas,
  getStepOrder,
  resolveOnboardingNextStep,
  resolveOnboardingPreviousStep,
} from "../onboarding/flow";
export {
  deriveOnboardingResumeConnection,
  deriveOnboardingResumeFields,
  hasPartialOnboardingConnectionConfig,
  inferOnboardingResumeStep,
} from "./onboarding-resume";
export {
  asApiLikeError,
  computeStreamingDelta,
  formatSearchBullet,
  formatStartupErrorDetail,
  mergeStreamingText,
  normalizeCustomActionName,
  normalizeStreamComparisonText,
  parseAgentStartupDiagnostics,
  parseAgentStatusEvent,
  parseAgentStatusFromMainMenuResetPayload,
  parseConversationMessageEvent,
  parseCustomActionParams,
  parseProactiveMessageEvent,
  parseSlashCommandInput,
  parseStreamEventEnvelopeEvent,
  shouldApplyFinalStreamText,
} from "./parsers";
export {
  applyUiTheme,
  clearPersistedConnectionMode,
  clearPersistedOnboardingStep,
  loadActiveConversationId,
  loadAvatarIndex,
  loadChatAvatarVisible,
  loadChatMode,
  loadChatVoiceMuted,
  loadCompanionAnimateWhenHidden,
  loadCompanionHalfFramerateMode,
  loadCompanionMessageCutoffTs,
  loadCompanionVrmPowerMode,
  loadLastNativeTab,
  loadPersistedConnectionMode,
  loadPersistedOnboardingComplete,
  loadPersistedOnboardingStep,
  savePersistedOnboardingComplete,
  loadUiLanguage,
  loadUiShellMode,
  loadUiTheme,
  normalizeCompanionHalfFramerateMode,
  normalizeCompanionVrmPowerMode,
  normalizeUiShellMode,
  normalizeUiTheme,
  type PersistedConnectionMode,
  saveActiveConversationId,
  saveAvatarIndex,
  saveChatAvatarVisible,
  saveChatMode,
  saveChatVoiceMuted,
  saveCompanionAnimateWhenHidden,
  saveCompanionHalfFramerateMode,
  saveCompanionMessageCutoffTs,
  saveCompanionVrmPowerMode,
  saveLastNativeTab,
  saveOnboardingStep,
  savePersistedConnectionMode,
  saveUiLanguage,
  saveUiShellMode,
  saveUiTheme,
  type UiTheme,
} from "./persistence";
export {
  type ActionNotice,
  AGENT_READY_TIMEOUT_MS,
  AGENT_STATES,
  AGENT_TRANSFER_MIN_PASSWORD_LENGTH,
  type AppActions,
  type AppContextValue,
  type AppState,
  type ChatTurnUsage,
  type CompanionHalfFramerateMode,
  type CompanionVrmPowerMode,
  type GamePostMessageAuthPayload,
  LIFECYCLE_MESSAGES,
  type LifecycleAction,
  type LoadConversationMessagesResult,
  type NavigationEventsApi,
  ONBOARDING_PERMISSION_LABELS,
  ONBOARDING_STEPS,
  type OnboardingMode,
  type OnboardingNextOptions,
  type OnboardingStep,
  type ShellView,
  type SlashCommandInput,
  type TabCommittedDetail,
  type StartupErrorReason,
  type StartupErrorState,
  type StartupPhase,
  type UiShellMode,
} from "./types";
export {
  TranslationProvider,
  type TranslationContextValue,
  useTranslation,
} from "./TranslationContext";
export { AppContext, useApp } from "./useApp";
export {
  getCompanionBackgroundUrl,
  getVrmBackgroundUrl,
  getVrmPreviewUrl,
  getVrmTitle,
  getVrmUrl,
  isOfficialVrmIndex,
  normalizeAvatarIndex,
  VRM_COUNT,
} from "./vrm";
